[package]
name = "ratatui-json-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.29.0"
serde = "1.0.215"
serde_json = "1.0.133"
